openapi: 3.0.0
info:
  title: Authentication API
  version: '1.0.0'
  description: API for user authentication

servers:
  - url: http://localhost:8080/api/v1

paths:
  # ------------------------
  # 🔐 AUTH - CUSTOMER
  # ------------------------
  /auth/customers/login:
    post:
      summary: Customer login (email, password or social login)

  /auth/customers/register:
    post:
      summary: Customer register account

  /auth/customers/refresh:
    post:
      summary: Refresh customer access token

  /auth/customers/logout:
    post:
      summary: Customer logout

  /auth/customers/forget-password:
    post:
      summary: Customer forgot password (request reset link)

  /auth/customers/change-password:
    patch:
      summary: Customer change password (authenticated user)

  # ------------------------
  # 🔐 AUTH - MANAGER / ADMIN
  # ------------------------
  /admin/auth/managers/login:
    post:
      summary: Manager login (admin panel)

  /admin/auth/managers/refresh:
    post:
      summary: Refresh manager access token

  /admin/auth/managers/logout:
    post:
      summary: Manager logout

  /admin/auth/managers/forget-password:
    post:
      summary: Manager forgot password (reset via email)

  /admin/auth/managers/change-password:
    patch:
      summary: Manager change password (authenticated admin)

components:
  responses:
    
    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: INVALID_INPUT
            messageEn: Invalid request parameters (format example)
            messageVn: Tham số yêu cầu không hợp lệ (ghi ra định dạng mẫu)

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: SERVER_ERROR
            messageEn: An unexpected error occurred
            messageVn: Đã xảy ra lỗi không mong muốn
