openapi: 3.0.0
info:
  title: Renter Service Public API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

security:
  - bearerAuth: []

paths:
  /feedback:
    get:
      summary: Get list of feedbacks
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Current page number (default 1)
        - in: query
          name: itemsPerPage
          schema:
            type: integer
          description: Number of items per page (default 20)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedbacks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Feedback'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '403':
          description: Unauthorized renter access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: UNAUTHORIZED_ACCESS
                messageEn: Unauthorized access
                messageVn: Truy cập không hợp lệ

    post:
      summary: Create a new feedback
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                renterId:
                  type: string
                driverId:
                  type: string
                bookingId:
                  type: string
                comment:
                  type: string
                rating:
                  type: integer
              required:
                - renterId
                - driverId
                - bookingId
                - comment
                - rating
      responses:
        '201':
          description: Feedback created successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: INVALID_INPUT
                messageEn: Invalid input data
                messageVn: Dữ liệu đầu vào không hợp lệ

    delete:
      summary: Delete feedback following filters
      responses:
        '204':
          description: Selected feedback deleted successfully
        '403':
          description: Unauthorized renter access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: UNAUTHORIZED_ACCESS
                messageEn: Unauthorized access
                messageVn: Truy cập không hợp lệ
      
components:
  schemas:
    Feedback:
      type: object
      properties:
        id:
          type: string
        renterId:
          type: string
        driverId:
          type: string
        bookingId:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string

    Pagination:
      type: object
      properties:
        totalItems:
          type: integer
        totalPages:
          type: integer
        currentPage:
          type: integer
        itemsPerPage:
          type: integer

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        messageEn:
          type: string
        messageVn:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
