openapi: 3.0.0
info:
  title: Renter API
  version: 1.0.0
  description: |
    The **Renter API** provides endpoints for managing renter information in the system.
    It allows clients (such as frontend or mobile applications) to:
      - Retrieve renter profiles and details
      - Update renter personal information
      - Access paginated lists of renters

    This API is typically used by the public-facing application layer and communicates
    with the Renter domain service internally.  
    Authentication is required via JWT bearer tokens.
    
servers:
  - url: http://localhost:8080/api/v1

security:
  - bearerAuth: []
  
paths:
  /renters:
    get:
      summary: Get list of renters
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Current page number (default 1)
        - in: query
          name: itemsPerPage
          schema:
            type: integer
          description: Number of items per page (default 20)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  renters:
                    type: array
                    items:
                      $ref: '#/components/schemas/Renter'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'


  /renters/{id}:
    get:
      summary: Get renter by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Renter'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    patch:
      summary: Update renter info
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '204':
          description: Updated successfully
        '400':
          $ref: '#/components/responses/InvalidInput'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    Renter:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        phone:
          type: string
        birthDate:
          type: string
          format: date
        avatar:
          type: string
        cumulativePoints:
          type: integer

    Pagination:
      type: object
      properties:
        totalItems:
          type: integer
        totalPages:
          type: integer
        currentPage:
          type: integer
        itemsPerPage:
          type: integer

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        messageEn:
          type: string
        messageVn:
          type: string

  responses:

    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: UNAUTHORIZED_ACCESS
            messageEn: Unauthorized access
            messageVn: Truy cập không hợp lệ
    
    NotFound:
      description: Renter not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: RENTER_NOT_FOUND
            messageEn: Renter not found
            messageVn: Không tìm thấy người thuê
    
    InvalidInput:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: INVALID_INPUT
            messageEn: Invalid request parameters (format example)
            messageVn: Tham số yêu cầu không hợp lệ (ghi ra định dạng mẫu)

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            errorCode: SERVER_ERROR
            messageEn: An unexpected error occurred
            messageVn: Đã xảy ra lỗi không mong muốn
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
