openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
  description: Provides endpoints related notifications for users.

servers:  
  - url: http://localhost:8080/api/v1

security:
  - bearerAuth: []

tags:
  - name: Notifications

paths:
  /notifications:
    get:
      tags:
        - Notifications
        - Administrative operations
      summary: Retrieve a list of notifications for the authenticated user.
      responses:
        '200':
          description: A list of notifications.
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
        '401':
          $ref: '../common/error_responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../common/error_responses.yaml#/components/responses/Forbidden'
        '500':
          $ref: '../common/error_responses.yaml#/components/responses/InternalServerError'

    post:
      tags:
        - Administrative operations
      summary: Create a new notification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '201':
          description: Notification created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          $ref: '../common/error_responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../common/error_responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../common/error_responses.yaml#/components/responses/Forbidden'
        '422':
          $ref: '../common/error_responses.yaml#/components/responses/UnprocessableEntity'
        '500':
          $ref: '../common/error_responses.yaml#/components/responses/InternalServerError'

  /notifications/{notificationId}:
    delete:
      tags:
        - Administrative operations
      summary: Delete a specific notification by its ID.
      parameters:
        - name: notificationId
          in: path
          required: true
          description: The ID of the notification to delete.
          schema:
            type: string
      responses:
        '204':
          description: Notification deleted successfully.
        '401':
          $ref: '../common/error_responses.yaml#/components/responses/Unauthorized'
        '403':
          $ref: '../common/error_responses.yaml#/components/responses/Forbidden'
        '404':
          $ref: '../common/error_responses.yaml#/components/responses/ResourceNotFound'
        '500':
          $ref: '../common/error_responses.yaml#/components/responses/InternalServerError'

components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createAt:
          type: string
          format: date-time
  
  securitySchemes:
    bearerAuth:
      $ref: '../common/security_schemes.yaml#/components/securitySchemes/bearerAuth'