openapi: 3.0.0
info:
  title: SayReal API
  version: 1.0.0
  description: API documentation for SayReal application.


servers:
- url:  http://localhost:8080/api/v1

security:
  - bearerAuth: []

paths:
  $ref: "./endpoints/drivers.yaml/paths"